### ISSUE TITLE
Test enchantment

### ISSUE THREAD

**Issue by Games4k** [Nova41/SnowLeopard#1]
Make it possible to test more people at the same time

**Comment by Nova41** [comment]
Hi Games4k,
Unfortunately, I am not planned to add this feature to the current project as the project is only for research purposes and not going to be an actual plugin.
However, I am designing a new project with an improved model, so everything could change in the future...

So you have to do it yourself. But it is pretty easy: just create more instances for testing.

**Comment by Games4k** [comment]
Thanks for the help. I did it ;P
Cant wait for new (yaw based) version
