### ISSUE TITLE
Cannot use command

### ISSUE THREAD

**Issue by buimanhduc** [Nova41/SnowLeopard#8]
Same as the title, please fix. Ty!

**Comment by Nova41** [comment]
Hi buimanhduc, the plugin is working correctly for me. Can you provide further information about the issue? i.e.  What shows up when you type /slr, /sl or /eac? Is there any error in the console? What version (Java & spigot) are you using currently? SnowLeopardR is compiled against Java 8 & spigot 1.12.2.

Aside from the above, I didn't specify the permission for the base command. If the issue have something to do with it, you can try to give yourself op as a temporarily workaround.

**Comment by Nova41** [comment]
Hi buimanhduc, the plugin is working correctly for me. Can you provide further information about the issue? i.e. What shows up when you type /slr, /sl or /eac? Is there any error in the console? What version (Java & spigot) are you using currently? SnowLeopardR is compiled against Java 8 & spigot 1.12.2.

Aside from the above, I didn't specify the permission for the base command. If the issue have something to do with it, you can try to op yourself as a temporarily workaround.

**Comment by buimanhduc** [comment]
Oh, I used the plugin on a 1.8.8 server and it has some errors, but 1 fixed it myself :>
All the sub command does not work, it only shows the help message 
![image](https://user-images.githubusercontent.com/50785623/60528451-aa1b3400-9d1e-11e9-9656-b1d08a8f4fa2.png)
, and the problem is the /slr command which has the sub command "", and the CommandManager.command() filter with startsWith(entry.get Key()) where entry.get Key() returns "" so matchedCommand is always the command which have the sub command "".
I dont think this problem is related to the spigot version. I use Java 8 too. I dont know why._.
So i made the default sub command "" to "help" and set the default command when no args are given to "help" and my problem is fixed :>

**Comment by Nova41** [comment]
Holy crap, thanks so much for the information.

**Comment by buimanhduc** [comment]
BTW can you write a training guide please, how to train it to get it's maximum potential =))
Your plugin is very nice, I love it :D

**Comment by Nova41** [comment]
Yeah I am absolutely willing to share my insights about training. But it would not be finished immediately. I only have time to release a version fixing the command bug today =)

**Comment by Nova41** [comment]
The bug is fixed I think. Could you test it if it is convenient for you?

**Comment by buimanhduc** [comment]
Oh nice work, the problem is fixed. Thank you so much. You are amazing :D
