### ISSUE TITLE
Too big difference, I think this is a bug

### ISSUE THREAD

**Issue by buimanhduc** [Nova41/SnowLeopard#9]
I accidentally found this when I was training the neutral networks. I am not sure is this a bug, but the difference up to 388339, it is a large number IDK.
![image](https://user-images.githubusercontent.com/50785623/60531714-c4a4db80-9d25-11e9-9a38-b703ded7a468.png)
Here is the config files: 
[SnowLeopardR.zip](https://github.com/Nova41/SnowLeopard/files/3351157/SnowLeopardR.zip)
Is this a bug? Please tell me
Thank you so much

**Comment by Nova41** [comment]
Samples look fine to me. Is it possible for you to provide the statistics of the neural network by /slr _printnn?

**Comment by buimanhduc** [comment]
Okay, it's here: https://gist.github.com/buimanhduc/38ace9834b7622480981b2a0613cef0a

**Comment by buimanhduc** [comment]
![image](https://user-images.githubusercontent.com/50785623/60560496-3dce1e00-9d7a-11e9-99ca-fd252f05e87d.png)
I have just tested it once and the difference keep around 388339.
My spigot version is 1.8.8, Java version is 1.8

**Comment by buimanhduc** [comment]
I use 1.8.8 because it provide the best PvP expericence, and most servers use it.

**Comment by Nova41** [comment]
Try tweaking network training parameters.

Lower the decrease rate & minimum step

On Jul 3, 2019, at 11:13 AM, Bùi Mạnh Đức <notifications@github.com<mailto:notifications@github.com>> wrote:


I use 1.8.8 because it provide the best PvP expericence, and most servers use it.

**Comment by Nova41** [comment]
Try tweaking network training parameters. Lower the decrease rate & minimum step

**Comment by buimanhduc** [comment]
Maybe my categories are broken. I think I will try to train it again =))
I use the default config.

**Comment by Nova41** [comment]
Alternatively you can try shuffling the dataset

**Comment by buimanhduc** [comment]
And can you fix the error when there is only one category, it throw 
array out of bound exception.
![image](https://user-images.githubusercontent.com/50785623/60564257-2f3b3300-9d89-11e9-9903-94bd5b582d54.png)

**Comment by Nova41** [comment]
Sure

But the likelihood makes no sense when there is only one category

**Comment by buimanhduc** [comment]
Oh okay, thanks
